$kind: http-example
request:
  url: '{{baseUrl}}/api/getToken'
  method: POST
  headers:
    Accept: application/json
response:
  statusCode: 500
  statusText: Internal Server Error
  headers:
    Content-Type: application/json; charset=utf-8
  body:
    type: json
    content: |-
      {
        "success": false,
        "error": "ADMIN_EMAIL or ADMIN_PASSWORD not set in .env"
      }
order: 3000
